import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const registry = readJson(path.join(root, "registry.json"));
const reportsDir = path.join(root, "reports");

const GENERATED = "<!-- Generated by scripts/generate-reports.js. Do not edit by hand. -->";

fs.mkdirSync(reportsDir, { recursive: true });

const tools = (registry.tools || [])
  .map((entry) => {
    const dir = path.join(root, entry.path || `tools/${entry.slug}`);
    const toolJson = readJson(path.join(dir, "tool.json"), {});
    const sourcesJson = readJson(path.join(dir, "sources.json"), []);
    const meta = { ...entry, ...toolJson };
    const sourceCounts = countSources(sourcesJson);
    const officialMcp = normalizeSurface(
      meta.surfaces?.officialMcp ?? meta.interfaces?.officialMcp ?? meta.officialMcp,
    );

    return {
      id: entry.id,
      name: entry.name || toolJson.name || entry.slug,
      slug: entry.slug || toolJson.slug,
      path: entry.path || `tools/${entry.slug}`,
      status: entry.status || toolJson.status || "unknown",
      score: Number(entry.agentReadinessScore ?? toolJson.agentReadinessScore ?? 0),
      lastVerified: entry.lastVerified || toolJson.lastVerified || "",
      canonicalUrl: toolJson.canonicalUrl || "",
      officialMcp,
      needsHumanReview: Boolean(toolJson.needsHumanReview),
      reviewReason: toolJson.reviewReason || "",
      sourceCounts,
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name, "en"));

const statusCounts = countBy(tools, (tool) => tool.status);
const scoreCounts = countBy(tools, (tool) => String(tool.score || "missing"));
const officialMcpCounts = countBy(tools, (tool) => tool.officialMcp);
const needsReview = tools.filter((tool) => tool.status === "needs-review" || tool.needsHumanReview);
const highReadiness = tools.filter((tool) => tool.score >= 5 && tool.status === "published");
const officialMcpTools = tools.filter((tool) => ["yes", "announced"].includes(tool.officialMcp));
const canonicalGaps = tools.filter((tool) => !tool.canonicalUrl);
const sourceGaps = tools.filter((tool) => tool.sourceCounts.total === 0);

writeReport("summary.md", renderSummary());
writeReport("needs-review.md", renderNeedsReview());
writeReport("high-readiness-tools.md", renderHighReadiness());
writeReport("official-mcp-tools.md", renderOfficialMcp());
writeReport("canonical-coverage.md", renderCanonicalCoverage());

console.log(`Generated 5 reports for ${tools.length} tools.`);

function renderSummary() {
  return [
    "# GTM Docs Registry Review Summary",
    "",
    GENERATED,
    "",
    `Generated from \`registry.json\` and \`tools/*/{tool.json,sources.json}\`.`,
    "",
    "## Counts",
    "",
    `- Total tools: ${tools.length}`,
    `- Needs review: ${needsReview.length}`,
    `- High-readiness published tools: ${highReadiness.length}`,
    `- Official MCP yes: ${officialMcpCounts.yes || 0}`,
    `- Official MCP announced: ${officialMcpCounts.announced || 0}`,
    "",
    "## Status Counts",
    "",
    renderCountTable(statusCounts, "Status"),
    "",
    "## Readiness Score Distribution",
    "",
    renderCountTable(scoreCounts, "Score", scoreSort),
    "",
    "## Official MCP Counts",
    "",
    renderCountTable(officialMcpCounts, "Official MCP"),
    "",
  ].join("\n");
}

function renderNeedsReview() {
  const rows = needsReview
    .sort(sortByStatusScoreName)
    .map((tool) => [
      linkTool(tool),
      tool.status,
      tool.score,
      tool.lastVerified || "-",
      tool.reviewReason || (tool.needsHumanReview ? "Flagged for human review." : "Status is needs-review."),
    ]);

  return [
    "# Needs Review",
    "",
    GENERATED,
    "",
    `Tools requiring review: ${needsReview.length} of ${tools.length}.`,
    "",
    table(["Tool", "Status", "Score", "Last Verified", "Reason"], rows),
    "",
  ].join("\n");
}

function renderHighReadiness() {
  const rows = highReadiness
    .sort((a, b) => b.score - a.score || a.name.localeCompare(b.name, "en"))
    .map((tool) => [
      linkTool(tool),
      tool.score,
      tool.officialMcp,
      tool.lastVerified || "-",
      sourceSummary(tool),
    ]);

  return [
    "# High Readiness Tools",
    "",
    GENERATED,
    "",
    `Published tools with readiness score 5: ${highReadiness.length}.`,
    "",
    table(["Tool", "Score", "Official MCP", "Last Verified", "Sources"], rows),
    "",
  ].join("\n");
}

function renderOfficialMcp() {
  const rows = officialMcpTools
    .sort((a, b) => mcpSort(a.officialMcp, b.officialMcp) || a.name.localeCompare(b.name, "en"))
    .map((tool) => [linkTool(tool), tool.officialMcp, tool.status, tool.score, tool.lastVerified || "-"]);

  return [
    "# Official MCP Tools",
    "",
    GENERATED,
    "",
    `Official MCP yes: ${officialMcpCounts.yes || 0}. Announced: ${officialMcpCounts.announced || 0}.`,
    "",
    table(["Tool", "Official MCP", "Status", "Score", "Last Verified"], rows),
    "",
  ].join("\n");
}

function renderCanonicalCoverage() {
  const rows = tools.map((tool) => [
    linkTool(tool),
    tool.canonicalUrl ? "yes" : "missing",
    sourceSummary(tool),
    tool.status,
    tool.score,
  ]);

  return [
    "# Canonical Coverage",
    "",
    GENERATED,
    "",
    `Tools with canonical URL: ${tools.length - canonicalGaps.length} of ${tools.length}.`,
    `Tools missing canonical URL: ${canonicalGaps.length}.`,
    `Tools with no sources: ${sourceGaps.length}.`,
    "",
    table(["Tool", "Canonical URL", "Sources", "Status", "Score"], rows),
    "",
  ].join("\n");
}

function readJson(filePath, fallback = undefined) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (error) {
    if (fallback !== undefined && error.code === "ENOENT") return fallback;
    throw error;
  }
}

function writeReport(fileName, content) {
  fs.writeFileSync(path.join(reportsDir, fileName), `${content.trimEnd()}\n`);
}

function normalizeSurface(value) {
  if (value === true) return "yes";
  if (value === false) return "no";
  if (typeof value === "string" && value.trim()) return value.trim().toLowerCase();
  return "unknown";
}

function countSources(sourcesJson) {
  if (Array.isArray(sourcesJson)) {
    return {
      official: sourcesJson.filter((source) => source.type === "official").length,
      community: sourcesJson.filter((source) => source.type === "community").length,
      total: sourcesJson.length,
    };
  }

  const official = Array.isArray(sourcesJson.official) ? sourcesJson.official.length : 0;
  const community = Array.isArray(sourcesJson.community) ? sourcesJson.community.length : 0;
  const other = Object.entries(sourcesJson)
    .filter(([key, value]) => !["lastVerified", "official", "community"].includes(key) && Array.isArray(value))
    .reduce((sum, [, value]) => sum + value.length, 0);

  return { official, community, total: official + community + other };
}

function countBy(items, getKey) {
  return items.reduce((counts, item) => {
    const key = getKey(item) || "unknown";
    counts[key] = (counts[key] || 0) + 1;
    return counts;
  }, {});
}

function renderCountTable(counts, label, sorter = alphaSort) {
  return table(
    [label, "Count"],
    Object.keys(counts)
      .sort(sorter)
      .map((key) => [key, counts[key]]),
  );
}

function table(headers, rows) {
  const escapedRows = rows.map((row) => row.map(escapeCell));
  return [
    `| ${headers.map(escapeCell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...escapedRows.map((row) => `| ${row.join(" | ")} |`),
  ].join("\n");
}

function escapeCell(value) {
  return String(value ?? "-").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function linkTool(tool) {
  return `[${tool.name}](../${tool.path}/tool.json)`;
}

function sourceSummary(tool) {
  const { official, community, total } = tool.sourceCounts;
  return `${total} total; ${official} official; ${community} community`;
}

function sortByStatusScoreName(a, b) {
  return a.status.localeCompare(b.status, "en") || b.score - a.score || a.name.localeCompare(b.name, "en");
}

function alphaSort(a, b) {
  return a.localeCompare(b, "en");
}

function scoreSort(a, b) {
  if (a === "missing") return 1;
  if (b === "missing") return -1;
  return Number(b) - Number(a);
}

function mcpSort(a, b) {
  const order = { yes: 0, announced: 1 };
  return (order[a] ?? 99) - (order[b] ?? 99);
}
